### PR TITLE
Fix showing of vault and old farms

### LINKED ISSUE #319: Fix Old Staking page before launching Vaults
image

### PR DESCRIPTION
**Pull request by medardm**
closes #319

### CODE REVIEW

**Review by EAdornado — APPROVED** [review]

File: src/config/constants/farms.ts [hunk 1]
```diff
@@ -59,29 +59,29 @@ const farms: FarmConfig[] = [
...
-  //   chain: MAINNET_CHAIN_ID,
-  //   token: tokens.mgg,
-  //   pairToken: tokens.busd,
-  //   quoteToken: tokens.mgg,
-  //   isPromoted: 1,
-  //   UIProps: farmsUIProps.LPmggBusd,
-  // },
   {
-    isMain: true,
+    isMain: false,
```
Comment (kojiadrianojr) [inline src/config/constants/farms.ts:63]: Pwede rin ba na if false, wag nalang lagyan? tho LGTM naman just wondering.

File: src/config/constants/pools.ts [hunk 2]
```diff
@@ -25,7 +25,7 @@ const pools: PoolConfig[] = [
   {
     // Fixed APR mainnet contract test
     isMain: true,
-    comingSoon: true,
+    comingSoon: false,
```
Comment (kojiadrianojr) [inline src/config/constants/pools.ts:28]: since naka optional naman to sa types, okay lang din ata na wala to. LGTM rin naman siya.

File: src/views/Gamefi/Gamefi.tsx [hunk 3]
```diff
@@ -73,11 +75,14 @@ const Gamefi: React.FC = () => {
   useEffect(() => {
     setStakedOnly(!isActive)
   }, [isActive])
-  const mggFarms = farmsLP.filter((farm) => farm.pid !== 0 && !farm.hasEnded && farm.isMain && !isArchivedPid(farm.pid))
-  const activeFarms = farmsLP.filter(
-    (farm) => farm.pid !== 0 && !farm.hasEnded && !farm.isMain && !isArchivedPid(farm.pid),
+
+  const vaultFarms = farmsLP.filter(
```
Comment (kojiadrianojr) [inline src/views/Gamefi/Gamefi.tsx:79]: LGTM

File: src/views/Gamefi/components/Cards/Farm.tsx [hunk 4]
```diff
@@ -95,7 +91,7 @@ const FarmCard2: React.FC<FarmCard2Props> = ({
         className="shodow-pop"
         style={{ cursor: 'pointer' }}
       >
-        <Link to={`/gamefi/${`LP`}/${farm.pid}`}>
+        <Link to={`/gamefi/${`LP`}/${farm.pid}`} style={farm.comingSoon ? { pointerEvents: 'none' } : {}}>
```
Comment (kojiadrianojr) [inline src/views/Gamefi/components/Cards/Farm.tsx:94]: Pwede rin to ata `style={farm.comingSoon && { pointerEvents: 'none'}}` ?

File: src/views/Gamefi/components/Cards/Farm.tsx [hunk 5]
```diff
@@ -131,7 +127,7 @@ const FarmCard2: React.FC<FarmCard2Props> = ({
             </Flex>
             <Flex style={{ justifyContent: 'end', alignItems: 'end' }}>
               <div style={{ textAlign: 'end' }}>
-                <Text color="white">APR {apr}</Text>
+                <Text color="white"> {apr ? `APR: ${apr}` : ''}</Text>
```
Comment (kojiadrianojr) [inline src/views/Gamefi/components/Cards/Farm.tsx:130]: Here naman, 

`{apr && <Text>APR: ${apr}</Text> }`

Note: Not exactly pero para maiwasan yung pag render parin ng component ng walang laman. tho might affect yung structure since nawala component.
